spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pixel_zone
    username: root
    password: '@Ph21112002'
  application:
    name: pixel-zone
springdoc:
  swagger-ui:
    path: '/api-docs'
server:
  port: 8081
